import { TahfidCenter } from '../types';

export const SEED_CENTERS: TahfidCenter[] = [
  {
    id: "istanbul-dar-al-qurra",
    name: "دار القراء بالفاتح",
    description: "مدرسة تاريخية لتحفيظ وتجويد القرآن الكريم في قلب إسطنبول. نرحب بالمسافرين والزوار لمراجعة الحفظ وتصحيح التلاوة في فناء مسجد الفاتح الأثري وتحت جنبات العمارة العثمانية العريقة.",
    lat: 41.0195,
    lng: 28.9498,
    address: "فناء مسجد الفاتح، علي كوشتشو، 34083 الفاتح",
    city: "إسطنبول",
    country: "تركيا",
    dropInWelcomed: true,
    gender: "mixed",
    ageGroups: ["youth", "adults"],
    languages: ["العربية", "الإنجليزية", "التركية"],
    recitationStyles: ["حفص"],
    operatingHours: "الحلقات الصباحية: 8:00 صباحاً - 11:00 صباحاً يومياً",
    teacherName: "الشيخ إبراهيم العثماني",
    contactEmail: "fatih.daralqurra@istanbulmail.com",
    contactPhone: "+90 532 111 2233",
    reviewsCount: 3,
    averageRating: 4.9,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "london-drop-in-kuttab",
    name: "جمعية شرق لندن للقرآن الكريم",
    description: "وجهة مثالية للعائلات المسلمة الزائرة للعاصمة لندن. نقدم حلقات مخصصة للشباب والأطفال المغتربين لمساعدتهم على متابعة أورادهم اليومية وحفظ القرآن الكريم دون تعقيد.",
    lat: 51.5175,
    lng: -0.0658,
    address: "طريق وايت تشابل، لندن E1 1JX",
    city: "لندن",
    country: "المملكة المتحدة",
    dropInWelcomed: true,
    gender: "mixed",
    ageGroups: ["children", "youth"],
    languages: ["العربية", "الإنجليزية"],
    recitationStyles: ["حفص"],
    operatingHours: "السبت والأحد: 10:00 صباحاً - 1:00 ظهراً",
    teacherName: "الأستاذ يوسف الرحمن",
    contactEmail: "el.quran@londoncommunity.org",
    contactPhone: "+44 20 7123 4567",
    reviewsCount: 2,
    averageRating: 4.5,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "cairo-traditional-kuttab",
    name: "مقرأة الأزهر الشريف بمصر القديمة",
    description: "عِش التجربة الروحية الأصيلة للكتاتيب المصرية التقليدية. نركز على الطرق الكلاسيكية في الحفظ مثل استخدام الألواح الخشبية والحبر التقليدي مع العناية بمخارج الحروف والتجويد.",
    lat: 30.0444,
    lng: 31.2612,
    address: "مسجد الغورية، الدرب الأحمر، محافظة القاهرة",
    city: "القاهرة",
    country: "مصر",
    dropInWelcomed: true,
    gender: "men",
    ageGroups: ["adults", "youth"],
    languages: ["العربية", "الإنجليزية", "الفرنسية"],
    recitationStyles: ["حفص", "ورش"],
    operatingHours: "بعد صلاة العصر: 5:00 مساءً - 8:00 مساءً يومياً",
    teacherName: "الشيخ محمود الشناوي",
    contactEmail: "azhar.kuttab@cairomail.eg",
    contactPhone: "+20 100 555 9876",
    reviewsCount: 4,
    averageRating: 5.0,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "casablanca-coastal-recitation",
    name: "معهد مسجد الحسن الثاني للتحفيظ",
    description: "حلقات قرآنية مهيبة تعقد داخل مكتبة مسجد الحسن الثاني المطل على المحيط الأطلسي. نتخصص في تلاوة ورش عن نافع (القراءة المغربية التقليدية) ونرحب بالزوار والمسافرين.",
    lat: 33.6083,
    lng: -7.6325,
    address: "شارع الكورنيش، الدار البيضاء 20000",
    city: "الدار البيضاء",
    country: "المغرب",
    dropInWelcomed: true,
    gender: "mixed",
    ageGroups: ["youth", "adults"],
    languages: ["العربية", "الفرنسية", "الإنجليزية"],
    recitationStyles: ["ورش"],
    operatingHours: "الإثنين والأربعاء: 6:00 مساءً - 8:30 مساءً",
    teacherName: "الشيخ الإدريسي المغربي",
    contactEmail: "hassan2.tahfid@mosquee.ma",
    contactPhone: "+212 522 99 88 77",
    reviewsCount: 2,
    averageRating: 4.8,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "kuala-lumpur-spiritual-oasis",
    name: "محراب القرآن بمسجد الولاية",
    description: "مرفق حديث ومريح للغاية يرحب بالجاليات والعائلات المسافرة. نوفر بيئة هادئة ومكيفة بالكامل لتسهيل الحفظ والمراجعة مع توفر مصليات مجهزة وساحات للأطفال.",
    lat: 3.1793,
    lng: 101.6775,
    address: "شارع توانكو عبد الحليم، مجمع الحكومي، 50480 كوالالمبور",
    city: "كوالالمبور",
    country: "ماليزيا",
    dropInWelcomed: true,
    gender: "mixed",
    ageGroups: ["children", "youth", "adults"],
    languages: ["العربية", "الإنجليزية", "الماليزية"],
    recitationStyles: ["حفص"],
    operatingHours: "يومياً: 9:00 صباحاً - 12:00 ظهراً",
    teacherName: "الأستاذ لقمان حكيم",
    contactEmail: "wilayah.quran@masjid.gov.my",
    contactPhone: "+60 3 6201 1234",
    reviewsCount: 1,
    averageRating: 4.0,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "medina-nabawi-associations",
    name: "حلقات المسجد النبوي الشريف",
    description: "اجلس كتفاً بكتف مع إخوانك من شتى أصقاع الأرض تحت المظلات البيضاء العملاقة للمسجد النبوي الشريف. نرحب بضيوف الرحمن والزوار للتلاوة وتصحيح القراءة على أيدي مشايخ معتمدين.",
    lat: 24.4672,
    lng: 39.6111,
    address: "المسجد النبوي الشريف، المدينة المنورة 42311",
    city: "المدينة المنورة",
    country: "المملكة العربية السعودية",
    dropInWelcomed: true,
    gender: "men",
    ageGroups: ["adults", "youth"],
    languages: ["العربية", "الإنجليزية", "الأوردية", "التركية", "الإندونيسية"],
    recitationStyles: ["حفص", "قالون", "ورش"],
    operatingHours: "بعد صلاة الفجر وبعد صلاة المغرب يومياً",
    teacherName: "الشيخ عبد القادر بن علي",
    contactEmail: "nabawi.associations@haramain.gov.sa",
    contactPhone: "+966 50 123 4567",
    reviewsCount: 5,
    averageRating: 5.0,
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const SEED_REVIEWS = [
  {
    id: "rev1",
    centerId: "istanbul-dar-al-qurra",
    userId: "traveler_demo_1",
    userName: "ساجد من برمنغهام",
    rating: 5,
    comment: "كانت هذه أفضل تجربة في رحلتي إلى إسطنبول! الشيخ إبراهيم كان ودوداً للغاية وصحح مخارج حروفي بصبر كبير. زرت المقرأة لثلاثة صباحات متتالية. سبحان الله، تلاوة القرآن في الفناء التاريخي تجربة لا تُنسى.",
    travelerOrigin: "برمنغهام، بريطانيا",
    welcomingScore: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: "rev2",
    centerId: "istanbul-dar-al-qurra",
    userId: "traveler_demo_2",
    userName: "أميرة من كوالالمبور",
    rating: 5,
    comment: "كامرأة مسافرة، كنت مترددة في البداية بشأن العثور على مكان مريح، لكن حلقة النساء هنا كانت منظمة ومرحبة للغاية. يتقنون العربية والإنجليزية بطلاقة. أنصح بها بشدة لكل زائر لإسطنبول!",
    travelerOrigin: "كوالالمبور، ماليزيا",
    welcomingScore: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: "rev3",
    centerId: "cairo-traditional-kuttab",
    userId: "traveler_demo_3",
    userName: "فرحان من تورونتو",
    rating: 5,
    comment: "الجلوس في القاهرة التاريخية واستخدام اللوح الخشبي والحبر التقليدي لكتابة الآيات كان شعوراً ساحراً! الشيخ محمود أستاذ قدير، وعلى الرغم من ضعف لغتي العربية فقد بذلوا قصارى جهدهم لمساعدتي.",
    travelerOrigin: "تورونتو، كندا",
    welcomingScore: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: "rev4",
    centerId: "london-drop-in-kuttab",
    userId: "traveler_demo_4",
    userName: "زيد من المدينة المنورة",
    rating: 4,
    comment: "أحضرت أطفالي إلى هنا خلال إجازتنا الصيفية في لندن. الأستاذ يوسف كان رائعاً معهم وساعدهم في الحفاظ على وردهم اليومي وتجنب الانقطاع. بيئة نظيفة وجميلة وتعرف أطفالي على أصدقاء جدد.",
    travelerOrigin: "المدينة المنورة، السعودية",
    welcomingScore: 4,
    createdAt: new Date().toISOString()
  },
  {
    id: "rev5",
    centerId: "medina-nabawi-associations",
    userId: "traveler_demo_5",
    userName: "عمر من باريس",
    rating: 5,
    comment: "لا شيء يضاهي تلاوة القرآن الكريم في المسجد النبوي الشريف. الحلقات مجانية ومتاحة دائماً والمعلمون من طراز عالمي. تجربة روحانية متكاملة يجب على كل معتمر أو زائر تجربتها.",
    travelerOrigin: "باريس، فرنسا",
    welcomingScore: 5,
    createdAt: new Date().toISOString()
  }
];
